### ISSUE TITLE
hello讨论个问题

### ISSUE THREAD

**Issue by ald2004** [FortiLeiZhang/model_zoo#2]
在mtcnn在serving以后pnet返回的还是一张图片大概5m的数组,是否能改成serving model之后直接返回box,请问你是怎么处理的?是需要在serving上再加一层wrap吗?

**Comment by FortiLeiZhang** [comment]
可以直接返归bbox，这样做的话需要将 __generateBoundingBox 函数放到 serving model 中实现。但是这个 serving model 中的 pnet/rnet/onet 只是搭了一个 CNN 的框架，放到 server 端用GPU来进行计算，而其他的控制、判断等过程都放到了本地的 CPU 上。之所以这么做是因为：首先 tensorflow 的 model 是 static 的，if ... else ... / for ... 等 condition 语句也是最近才开始支持的，所以，尽量不把这些放到 tensorflow 中实现，而是拿到 serving model 外用 numpy 实现。其次，尽量用 GPU 来做运算，而不去处理其他 CPU 可以做的工作。

**Comment by ald2004** [comment]
非常感谢你有时间回复.
但是如果if else都放到cpu上来实现的话,一个图片几百k,client和tensorflow serving之间传输这些box数组需要大概5m的数据,那serving看上去就失去了意义,还有一种方式我看老外他们会在serving的上层warp一层webserver,但是这样做的话serving的意义又没有了.
另外把__generateBoundingBox 函数放到serving model中实现需要全部使用tensorflow的函数,难度确实有点大,不知道你们是使用的那种方式实现,谢谢.
